<?php
//***********includes.php**************
//Created by Philippe Nong
//Contact: philippe.nong@efc2-consulting.com
//Created: 21/07/2017
//Last modified: 15/11/2017


//////////// A supprimer une fois toutes connexions remplacees par execute_query ///////////////////////


//function to execute a SQL query
function exec_query($connection, $query){
	$result = mysqli_query($connection, $query);
	if($result){
		return $result;
	}
	else {
		echo 'Error executing the query.' . "<br />\n";
		echo 'Message from MySQL:' . mysql_error($connection);
		exit;
	}
}
// Connect to the server and database for multiquery queries
function multiquery_connect_db(){
	$con = new mysqli(HOST, USERNAME, PASSWORD, DBNAME);
	setlocale (LC_TIME, 'fr_FR.utf8','fra');
	if ($con->connect_error) {
		die("Connection failed: " . $con->connect_error);
	}
	return $con;
}

//////////// A supprimer une fois toutes connexions remplacees par execute_query ///////////////////////


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////       Connection to database and query mmanagement      ///////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////
function connect_db(){
	//Connection to the server and database
	$result = mysqli_connect(HOST, USERNAME, PASSWORD, DBNAME);
	setlocale (LC_TIME, 'fr_FR.utf8','fra');
	if(!$result){
		echo 'Could not connect to the server. Please try again later or contact the webmaster.';
	}
	else return $result;
}
//Connect to the database and execute multiple SQL queries
function execute_multiquery($query){
	//$con = multiquery_connect_db();
	$con = new mysqli(HOST, USERNAME, PASSWORD, DBNAME);
	setlocale (LC_TIME, 'fr_FR.utf8','fra');
	mysqli_set_charset($con, "utf8");
	if ($con->connect_error) {
		die("Connection failed: " . $con->connect_error);
	}
	if($con->multi_query($query)){
		do{
			$con->next_result();
		} while ($con->more_results());
	}
	if($con->errno){
		die("Erreur " . $con->error);
	}
	$con->close();
}
//Connect to the database and execute a single SQL query
function execute_query($query){
	$con = mysqli_connect(HOST, USERNAME, PASSWORD, DBNAME);
	mysqli_set_charset($con, "utf8");
	setlocale (LC_TIME, 'fr_FR.utf8', 'fra');
	if(!$con){
		echo 'Could not connect to the server. Please try again later or contact the webmaster.';
	    printf("Échec de la connexion : %s\n", mysqli_connect_error());
    	exit();	
	}
	else {
		$result = mysqli_query($con, $query);
		
		if($result){
			return $result;
		}
		else {
			echo 'Error executing the query.' . "<br />\n";
			printf('Message from MySQL :', mysqli_error($con));
			exit();
		}
		mysqli_close($con);
	}
}

//Function to get the next object of the result of a query
function next_object($result){
	return mysqli_fetch_object($result);
}

//Function to get the next object as an array that corresponds to the fetched row
function next_row($result){
	return mysqli_fetch_row($result);
}

//Function to get the next object as an array (label,content) of the result of a query
function next_line($result){
	return mysqli_fetch_assoc($result);
}

//Function to get all the results of a query in an array
function array_result($result_query){
	//$result = array();
	while($row = next_line($result_query)){
		$result[] = $row;
	}
	return $result;
}

function array_result_no_null($result_query){
	if($result_query){
		$data = [];
	if(mysqli_num_rows($result_query) > 0) {
		while($row = next_line($result_query)){
			foreach ($row as $key => $val) { 
				if (is_null($val)) {
					$row[$key] = 0;
				}
			}
			$data [] = $row;
		}
	}
	return $data;
}
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////    End connection to database and query management      ////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////











///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//Création d'une nouvelle garde
function insert_garde($id_pharma, $date_debut, $date_fin, $con){
	$query = "INSERT INTO GARDES (ID_PHARMA, DATE_DEBUT, DATE_FIN) VALUES ('$id_pharma', STR_TO_DATE('$date_debut', '%d/%m/%Y'), STR_TO_DATE('$date_fin', '%d/%m/%Y'))";
	$result = mysqli_query($con,$query);
	if($result){
			echo "Garde du {$_POST['date_debut_garde']} créée";
	}
	else {
		echo '<p><font color=red>Erreur système.</font></p>';
	}
}

//Function to display all the gardes selected within date_debut_garde and date_fin_garde
function display_garde($date_debut_garde, $date_fin_garde, $con){
	//Affiche les pharmacies répondant aux critères
	$query = "SELECT ID_GARDE, DATE_DEBUT, DATE_FIN, NOM_PHARMA, ADRESSE, VILLE, TELEPHONE FROM PHARMACIES P, GARDES G WHERE G.DATE_DEBUT>= STR_TO_DATE('". $date_debut_garde . "', '%d/%m/%Y') AND G.DATE_FIN<= STR_TO_DATE('". $date_fin_garde . "', '%d/%m/%Y') AND G.ID_PHARMA=P.ID_PHARMA ORDER BY G.DATE_DEBUT ASC";
	$result = mysqli_query($con,$query);
	if($result){
		if(mysqli_num_rows($result) > 0) {
			setlocale (LC_TIME, 'fr_FR.utf8','fra');
			while($row = next_line($result)){
				echo "<TR><TD>";
				$telephone = formatPhone($row["TELEPHONE"]);
				if($row["DATE_DEBUT"] == $row["DATE_FIN"])
					echo "Le " . formatDateText($row["DATE_DEBUT"]);
				else
					echo "Du " .  formatDateText($row["DATE_DEBUT"]) . " Au ".  formatDateText($row["DATE_FIN"]);
				echo "</TD><TD>" . $row["NOM_PHARMA"] . "</TD><TD>" . $row["ADRESSE"] . "</TD><TD>" . $row["VILLE"] . "</TD><TD>" . $telephone . "</TD><TD>";
				echo display_button("maj_garde.php?idGarde=" . $row["ID_GARDE"], "ico_modifier.png", "Modifier") . "</TD><TD>";
				echo display_button($_SERVER['PHP_SELF'] . "?idGarde=" . $row["ID_GARDE"] . "&dateDebut=" . $date_debut_garde . "&dateFin=" . $date_fin_garde , "ico_supprimer.png", "Supprimer") . "</TD></TR>";
			}
		}			
	}
	else {
		echo '<p><font color=red>Erreur système.</font></p>';
	}
}


//Function to update a garde
function update_garde($id_garde, $con){
	$query = "SELECT ID_GARDE, G.ID_PHARMA AS ID_PHARMA, DATE_DEBUT, DATE_FIN FROM GARDES G, PHARMACIES P WHERE ID_GARDE=" . $id_garde . " AND G.ID_PHARMA=P.ID_PHARMA";
	$result = mysqli_query($con,$query);
	if(false !== $result){
		$row= next_line($result);
		return $row;
	}
}

//Liste des pharmacies du secteur
function liste_pharma($con){
	$query = "SELECT ID_PHARMA, NOM_PHARMA, NOM_TITULAIRE, ADRESSE, VILLE, TELEPHONE FROM PHARMACIES ORDER BY NOM_PHARMA ASC";
	$result = mysqli_query($con,$query);
		if($result)
			return $result;
		else 
			echo '<p><font color=red>Erreur système.</font></p>';
}

//Affiche la liste des pharmacies de garde dans un tableau pour créer une nouvelle garde
function display_liste_pharma_insert($con){
	$query = "SELECT ID_PHARMA, NOM_PHARMA, NOM_TITULAIRE, ADRESSE, VILLE, TELEPHONE FROM PHARMACIES ORDER BY NOM_PHARMA ASC";
	$result = mysqli_query($con,$query);
	if(false !== $result){
		if(mysqli_num_rows($result) > 0){ 
			echo '<select multiple size=30 name="id_pharma">';        
			while($row = next_line($result)){ 
				echo '<option value="', $row["ID_PHARMA"], '">', $row["NOM_PHARMA"] , ' (', $row["NOM_TITULAIRE"] , ')</option>';			
			}  
        echo '</select>'; 
		} 
		mysqli_free_result($result);     
	}
}

//Affiche la liste des pharmacies de garde dans un tableau et se positionne sur la pharmacie par défaut
function display_liste_pharma_update($con, $row_modif){
	$query = "SELECT ID_PHARMA, NOM_PHARMA, NOM_TITULAIRE, ADRESSE, VILLE, TELEPHONE FROM PHARMACIES ORDER BY NOM_PHARMA ASC";
	$result = mysqli_query($con,$query);
	if(false !== $result) {
		if(mysqli_num_rows($result) > 0) { 
			echo '<select multiple size=30 name="id_pharma">';        
			while($row = next_line($result)){ 
				if ($row["ID_PHARMA"] == $row_modif["ID_PHARMA"])
					echo '<option value="', $row["ID_PHARMA"], '" selected>', $row["NOM_PHARMA"] , ' (', $row["NOM_TITULAIRE"] , ')</option>';			
				else
					echo '<option value="', $row["ID_PHARMA"], '">', $row["NOM_PHARMA"] , ' (', $row["NOM_TITULAIRE"] , ')</option>';
			}  
			echo '</select>'; 
		} 
		mysqli_free_result($result);     
	}			
	else 
		echo '<p><font color=red>Erreur système.</font></p>';	
}

//Return an array of the data to print
function display_list_to_print($con, $date_debut_garde, $date_fin_garde){
	$query = "SELECT ID_GARDE, DATE_DEBUT, DATE_FIN, NOM_PHARMA, ADRESSE, VILLE, TELEPHONE FROM PHARMACIES P, GARDES G WHERE G.DATE_DEBUT>= STR_TO_DATE('". $date_debut_garde . "', '%d/%m/%Y') AND G.DATE_FIN<= STR_TO_DATE('". $date_fin_garde . "', '%d/%m/%Y') AND G.ID_PHARMA=P.ID_PHARMA ORDER BY G.DATE_DEBUT ASC";
	$result = mysqli_query($con,$query);
	$data = array();
	while($row = next_line($result)){
		if($row["DATE_DEBUT"] == $row["DATE_FIN"])
			$date = "Le " . formatDateText($row["DATE_DEBUT"]);
		else 
			$date =  "Du " .  formatDateText($row["DATE_DEBUT"]) . " Au ".  formatDateText($row["DATE_FIN"]);
		$pharmacie = $row["NOM_PHARMA"];
		$adresse =  $row["ADRESSE"];
		$ville = $row["VILLE"];
		$telephone = formatPhone($row["TELEPHONE"],0,2);
		
		$data[] = array(iconv('UTF-8', 'ISO-8859-1//TRANSLIT',$date), $pharmacie, $adresse, $ville, $telephone);
	}
	return $data;
}


//Calcule les sig d'une société. et les enregistre ou les mets à jour dans la table SIG
function soldes_intermediaires_gestion($con, $id_societe){
	$query = "SELECT ID_BILAN, B.ID_SOCIETE AS ID_SOCIETE, ANNEE_BILAN, CAPITAL_SOUSCRIT_NON_APPELE, FRAIS_ETABLISSEMENT, FRAIS_ETABLISSEMENT_AMORTISSEMENT_PROVISIONS, FRAIS_DEVELOPPEMENT, FRAIS_DEVELOPPEMENT_AMORTISSEMENT_PROVISIONS, CONCESSION_BREVET, CONCESSION_BREVET_AMORTISSEMENT_PROVISIONS, FOND_COMMERCIAL, FOND_COMMERCIAL_AMORTISSEMENT_PROVISIONS, AUTRES_IMMO_INCORPORELLES, AUTRES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS, AVANCES_ACOMPTES_IMMO_INCORPORELLES, AVANCES_ACOMPTES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS, TERRAIN, TERRAIN_AMORTISSEMENT_PROVISIONS, CONSTRUCTION, CONSTRUCTION_AMORTISSEMENT_PROVISIONS, INSTALLATIONS_TECHNIQUES, INSTALLATIONS_TECHNIQUES_AMORTISSEMENT_PROVISIONS, AUTRES_IMMO_CORPORELLES, AUTRES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS, IMMO_ENCOURS, IMMO_ENCOURS_AMORTISSEMENT_PROVISIONS, AVANCES_ACOMPTES_IMMO_CORPORELLES, AVANCES_ACOMPTES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS, PARTICIPATION, PARTICIPATION_AMORTISSEMENT_PROVISIONS, AUTRES_PARTICIPATIONS, AUTRES_PARTICIPATIONS_AMORTISSEMENT_PROVISIONS, CREATIONS_RATTACHEES_PARTICIPATION, CREATIONS_RATTACHEES_PARTICIPATION_AMORTISSEMENT_PROVISIONS, AUTRES_TITRES_IMMOBILISES, AUTRES_TITRES_IMMOBILISES_AMORTISSEMENT_PROVISIONS, PRETS, PRETS_AMORTISSEMENT_PROVISIONS, AUTRES_IMMOBILISATIONS_FINANCIERES, AUTRES_IMMOBILISATIONS_FINANCIERES_AMORTISSEMENT_PROVISIONS, MATIERE_PREMIERE_APPROVISIONNEMENT, MATIERE_PREMIERE_APPROVISIONNEMENT_AMORTISSEMENT_PROVISIONS, EN_COURS_PRODUCTION_BIENS, EN_COURS_PRODUCTION_BIENS_AMORTISSEMENT_PROVISIONS, EN_COURS_PRODUCTION_SERVICES, EN_COURS_PRODUCTION_SERVICES_AMORTISSEMENT_PROVISIONS, PRODUITS_INTERMEDIAIRE_FINI, PRODUITS_INTERMEDIAIRE_FINI_AMORTISSEMENT_PROVISIONS, MARCHANDISE, MARCHANDISE_AMORTISSEMENT_PROVISIONS, AVANCES_ACOMPTES_VERSES_COMMANDE, AVANCES_ACOMPTES_VERSES_COMMANDE_AMORTISSEMENT_PROVISIONS, CLIENTS_COMPTES_RATTACHES, CLIENTS_COMPTES_RATTACHES_AMORTISSEMENT_PROVISIONS, AUTRES_CREANCES, AUTRES_CREANCES_AMORTISSEMENT_PROVISIONS, CAPITAL_SOUSCRIT_APPELE_NON_VERSE, CAPITAL_SOUSCRIT_APPELE_NON_VERSE_AMORTISSEMENT_PROVISIONS, VALEUR_MOBILIERE_PLACEMENT, VALEUR_MOBILIERE_PLACEMENT_AMORTISSEMENT_PROVISIONS, DISPONIBILITES, DISPONIBILITES_AMORTISSEMENT_PROVISIONS, CHARGES_CONSTATEES_AVANCE, CHARGES_CONSTATEES_AVANCE_AMORTISSEMENT_PROVISIONS, FRAIS_EMISSION_EMPRUNT, PRIME_REMBOURSEMENT_OBLIGATIONS, ECART_CONVERSION_ACTIF, CAPITAL_SOCIAL, PRIME_EMISSION, ECART_REEVALUATION, RESERVE_LEGALE, RESERVE_STATUTAIRE, RESERVE_REGLEMENTEE, AUTRES_RESERVES, REPORT_A_NOUVEAU, RESULTAT_EXERCICE, SUBVENTION_INVESTISSEMENT, PROVISION_REGLEMENTEE, PRODUIT_EMISSION_TITRES_PARTICIPATIFS, AVANCE_CONDITIONNEE, PROVISION_RISQUE, PROVISION_CHARGE, EMPRUNT_OBLIGATAIRE_CONVERTIBLE, AUTRE_EMPRUNT_OBLIGATAIRE, EMPRUNT_DETTE_ETABLISSEMENT_CREDIT, EMPRUNT_DETTE_FINANCIERE_DIVERS, AVANCE_ACOMPTE_RECU_COMMANDE_EN_COURS, DETTE_FOURNISSEUR, DETTE_FISCALE_SOCIALE, DETTE_IMMO, AUTRES_DETTES, PRODUITS_CONSTATES_AVANCE, ECART_CONVERSION_PASSIF, DONT_RESERVE_SPECIALE_REEVALUATION, DONT_ECART_REEVALUATION_LIBRE, DONT_RESERVE_REEVALUATION, DONT_RESERVE_SPECIALE_PLUS_VALUE_LONG_TERME, DETTE_PRODUIT_CONSTATE_AVANCE_MOINS_UN_AN, DONT_CONCOURS_BANCAIRE_COURANT, VENTE_MARCHANDISE_FRANCE, VENTE_MARCHANDISE_EXPORT, PRODUCTION_VENDUE_BIENS_FRANCE, PRODUCTION_VENDUE_BIENS_EXPORT, PRODUCTION_VENDUE_SERVICE_FRANCE, PRODUCTION_VENDUE_SERVICE_EXPORT, PRODUCTION_STOCKEE, PRODUCTION_IMMOBILISEE, SUBVENTION_EXPLOITATION, REPRISE_AMORTISSEMENT_PROVISION_TRANSFERT_CHARGE, AUTRE_PRODUIT, ACHAT_MARCHANDISES, VARIATION_STOCK, ACHAT_MATIERE_PREMIERE, VARIATION_STOCK_MP, AUTRE_ACHAT_CHARGE_EXTERNE, IMPOT_TAXE, SALAIRE, CHARGE_SOCIALE, DOTATION_AMORTISSEMENT_IMMO, DOTATION_PROVISION_IMMO, DOTATION_PROVISION_ACTIF_CIRCULANT, DOTATION_PROVISION_RISQUE_CHARGE, AUTRE_CHARGE, BENEFICE_ATTRIBUE_PERTE_TRANSFEREE, PERTE_SUPPORTEE_BENEFICE_TRANSFERE, PRODUIT_FINANCIER_PARTICIPATION, PRODUIT_AUTRE_VALEUR_MOBILIERE, AUTRE_INTERET_PRODUIT_ASSIMILE, REPRISE_PROVISIONS_TRANSFERT_CHARGE_FINANCIERE, DIFFERENCE_POSITIVE_CHANGE, PRODUIT_NET_CESSION_VALEUR_MOBILIERE_PLACEMENT, DOTATION_FINANCIERE_AMORTISSEMENT_PROVISION, INTERET_CHARGE_ASSIMILEE, DIFFERENCE_NEGATIVE_CHANGE, CHARGE_NETTE_CESSION_VALEUR_MOBILIERE_PLACEMENT, PRODUIT_EXCEPTIONNEL_OPERATION_GESTION, PRODUIT_EXCEPTIONNEL_OPERATION_CAPITAL, REPRISE_PROVISIONS_TRANSFERT_CHARGE_EXCEPT, CHARGE_EXCEPTIONNELLE_OPERATION_GESTION, CHARGE_EXCEPTIONNELLE_OPERATION_CAPITAL, DOTATION_EXCEPTIONNELLE_AMORTISSEMENT_PROVISION, PARTICIPATION_SALARIE, IMPOT_BENEFICE, DONT_CREDIT_BAIL_MOBILIER, DONT_CREDIT_BAIL_IMMOBILIER, ENGAGEMENT_CREDIT_BAIL_MOBILIER, ENGAGEMENT_CREDIT_BAIL_IMMOBILIER, EFFET_PORTE_ESCOMPTE_NON_ECHU, SOUS_TRAITANCE, LOCATION, PERSONNEL_EXT, REMUNERATION_INTERMEDIAIRE, RETROCESSION_HONORAIRE, AUTRE_COMPTE, TAXE_PROFESSIONNELLE_CFE_CVAE, AUTRE_IMPOT, TVA_COLLECTEE, TVA_DEDUCTIBLE, SALAIRE_BRUT, PLUS_VALUE_FRANCHISE_IMPOT, EFFECTIF_MOYEN, ENCOURS_AFFACTURAGE, NOM_SOCIETE, FIN_BILAN 
		FROM BILAN B, SOCIETE S WHERE B.ID_SOCIETE=S.ID_SOCIETE AND S.ID_SOCIETE=" . $id_societe . ";"; //AND ANNEE_BILAN='2016'";
		$result = exec_query($con, $query);	
	if(false != $result) {
		while($bilan = next_line($result)){
			$VENTE_MARCHANDISE = $bilan['VENTE_MARCHANDISE_FRANCE'] + $bilan['VENTE_MARCHANDISE_EXPORT'];
			$COUT_ACHAT_MARCHANDISES_VENDUES = $bilan['ACHAT_MARCHANDISES'] + $bilan['VARIATION_STOCK'] ;
			$MARGE_COMMERCIALE = $VENTE_MARCHANDISE - $COUT_ACHAT_MARCHANDISES_VENDUES ;
			$PRODUCTION_VENDUE = $bilan['PRODUCTION_VENDUE_BIENS_FRANCE'] + $bilan['PRODUCTION_VENDUE_BIENS_EXPORT'] + $bilan['PRODUCTION_VENDUE_SERVICE_FRANCE'] + $bilan['PRODUCTION_VENDUE_SERVICE_EXPORT'];
			$PRODUCTION_STOCKEE =  $bilan['PRODUCTION_STOCKEE'];
			$PRODUCTION_IMMOBILISEE = $bilan['PRODUCTION_IMMOBILISEE'];
			$PRODUCTION = $PRODUCTION_VENDUE + $PRODUCTION_STOCKEE + $PRODUCTION_IMMOBILISEE;
			$CONSOMMATION_MATIERE_PREMIERE = $bilan['ACHAT_MATIERE_PREMIERE'] + $bilan['VARIATION_STOCK_MP'];
			$MARGE_BRUTE_PRODUCTION = $PRODUCTION - $CONSOMMATION_MATIERE_PREMIERE;
			$MARGE_BRUTE = $MARGE_COMMERCIALE + $MARGE_BRUTE_PRODUCTION;
			$AUTRES_ACHATS_CHARGES_EXTERNES = $bilan['AUTRE_ACHAT_CHARGE_EXTERNE'];
			$CORRECTIONS = $bilan['DONT_CREDIT_BAIL_MOBILIER'] - $bilan['PERSONNEL_EXT'];
			$VA = $MARGE_BRUTE - $AUTRES_ACHATS_CHARGES_EXTERNES - $CORRECTIONS;
			$SUBVENTION_EXPLOITATION = $bilan['SUBVENTION_EXPLOITATION'];
			$FRAIS_PERSIONNEL = $bilan['SALAIRE'] + $bilan['CHARGE_SOCIALE'];
			$RECLASSEMENT_INTERIM = $bilan['PERSONNEL_EXT'];
			$IMPOTS_TAXES = $bilan['IMPOT_TAXE'];	
			$EBE = $VA + $SUBVENTION_EXPLOITATION - $FRAIS_PERSIONNEL - $RECLASSEMENT_INTERIM - $IMPOTS_TAXES;
			$AUTRES_PRODUITS = $bilan['AUTRE_PRODUIT'];
			$AUTRES_CHARGES = $bilan['AUTRE_CHARGE'];
			$DOTATIONS_AMORTISSEMENTS = $bilan['DOTATION_AMORTISSEMENT_IMMO'];
			$RECLASSEMENT_CREDIT_BAIL = $bilan['DONT_CREDIT_BAIL_MOBILIER']*0.75  +  $bilan['DONT_CREDIT_BAIL_IMMOBILIER']*2/3;
			$DOTATION_PROVISIONS_NETTES_REPRISES = $bilan['DOTATION_PROVISION_IMMO'] + $bilan['DOTATION_PROVISION_ACTIF_CIRCULANT'] + $bilan['DOTATION_PROVISION_RISQUE_CHARGE'] - $bilan['REPRISE_AMORTISSEMENT_PROVISION_TRANSFERT_CHARGE'];
			$REX = $EBE  + $AUTRES_PRODUITS -  $AUTRES_CHARGES -  $DOTATIONS_AMORTISSEMENTS - $RECLASSEMENT_CREDIT_BAIL - $DOTATION_PROVISIONS_NETTES_REPRISES;
			$PRODUITS_FINANCIERS = $bilan['PRODUIT_FINANCIER_PARTICIPATION'] + $bilan['PRODUIT_AUTRE_VALEUR_MOBILIERE'] + $bilan['AUTRE_INTERET_PRODUIT_ASSIMILE'] + $bilan['REPRISE_PROVISIONS_TRANSFERT_CHARGE_FINANCIERE'] + $bilan['DIFFERENCE_POSITIVE_CHANGE'] + $bilan['PRODUIT_NET_CESSION_VALEUR_MOBILIERE_PLACEMENT'];
			$CHARGES_FINANCIERES = $bilan['DOTATION_FINANCIERE_AMORTISSEMENT_PROVISION'] + $bilan['INTERET_CHARGE_ASSIMILEE'] + $bilan['DIFFERENCE_NEGATIVE_CHANGE'] + $bilan['CHARGE_NETTE_CESSION_VALEUR_MOBILIERE_PLACEMENT'];
			$RECLASSEMENT_CREDIT_BAIL_FIN = $bilan['DONT_CREDIT_BAIL_MOBILIER']*0.25  +  $bilan['DONT_CREDIT_BAIL_IMMOBILIER']*1/3;
			$RFINANCIER =  $PRODUITS_FINANCIERS - $CHARGES_FINANCIERES - $RECLASSEMENT_CREDIT_BAIL_FIN;
			$RESULTAT_COURANT_AVANT_IS = $REX + $RFINANCIER;
			$RESULTAT_EXCEPTIONNEL = $bilan['PRODUIT_EXCEPTIONNEL_OPERATION_GESTION'] + $bilan['PRODUIT_EXCEPTIONNEL_OPERATION_CAPITAL'] + $bilan['REPRISE_PROVISIONS_TRANSFERT_CHARGE_EXCEPT'] - $bilan['CHARGE_EXCEPTIONNELLE_OPERATION_GESTION'] - $bilan['CHARGE_EXCEPTIONNELLE_OPERATION_CAPITAL'] - $bilan['DOTATION_EXCEPTIONNELLE_AMORTISSEMENT_PROVISION'];
			$PARTICIPATION_SALARIES = $bilan['PARTICIPATION_SALARIE'] ;
			$IS = $bilan['IMPOT_BENEFICE'];
			$RESULTAT_NET = $RESULTAT_COURANT_AVANT_IS + $RESULTAT_EXCEPTIONNEL - $PARTICIPATION_SALARIES - $IS;
			$DOTATION_PROVISIONS_CARACTERE_RESERVES = $bilan['DOTATION_EXCEPTIONNELLE_AMORTISSEMENT_PROVISION'] - $bilan['REPRISE_PROVISIONS_TRANSFERT_CHARGE_EXCEPT'];
			$PLUS_VALUE_CESSION = $bilan['PRODUIT_EXCEPTIONNEL_OPERATION_CAPITAL'] - $bilan['CHARGE_EXCEPTIONNELLE_OPERATION_CAPITAL'];
			$CAF = $RESULTAT_NET + $DOTATIONS_AMORTISSEMENTS + $RECLASSEMENT_CREDIT_BAIL + $DOTATION_PROVISIONS_CARACTERE_RESERVES - $PLUS_VALUE_CESSION;
			$NOPAT = $REX*(1-$IS/$RESULTAT_COURANT_AVANT_IS);
				
			$query_sig = "SELECT ID_SOCIETE, ANNEE_BILAN FROM SIG WHERE ID_SOCIETE = " . $bilan['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $bilan['ANNEE_BILAN'] . "'";
			$result_sig = exec_query($con, $query_sig);
			if(next_object($result_sig)) {
				$query_update_sig = "UPDATE SIG SET VENTE_MARCHANDISE=" . $VENTE_MARCHANDISE . ", COUT_ACHAT_MARCHANDISE=" . $COUT_ACHAT_MARCHANDISES_VENDUES . " ,	MARGE_COMMERCIALE=" . $MARGE_COMMERCIALE . 
					" , PRODUCTION_VENDUE=" . $PRODUCTION_VENDUE . " , PRODUCTION_STOCKEE=" . $PRODUCTION_STOCKEE  . " , PRODUCTION_IMMOBILISEE=" . $PRODUCTION_IMMOBILISEE . " , PRODUCTION=" . $PRODUCTION . 
					" , CONSOMMATION_MATIERE_PREMIERE=" . $CONSOMMATION_MATIERE_PREMIERE . " , MARGE_BRUTE=" . $MARGE_BRUTE . " , AUTRE_ACHAT_CHARGE_EXTERNE=" . $AUTRES_ACHATS_CHARGES_EXTERNES . ", CORRECTION=" . $CORRECTIONS . 
					" , VALEUR_AJOUTEE=" . $VA . " , SUBVENTION_EXPLOITATION=" . $SUBVENTION_EXPLOITATION . " , FRAIS_PERSONNEL=" . $FRAIS_PERSIONNEL . " , RECLASSEMENT_INTERIM=" . $RECLASSEMENT_INTERIM . 
					" , IMPOTS_TAXE=" . $IMPOTS_TAXES . " , EBE=" . $EBE . " , AUTRE_PRODUIT=" . $AUTRES_PRODUITS . " , AUTRE_CHARGE=" . $AUTRES_CHARGES . " , DOTATION_AMORTISSEMENT=" . $DOTATIONS_AMORTISSEMENTS . 
					" , RECLASSEMENT_CREDIT_BAIL=" . $RECLASSEMENT_CREDIT_BAIL . " , DOTATION_PROVISION_NETTE_REPRISE=" . $DOTATION_PROVISIONS_NETTES_REPRISES . " , RESULTAT_EXPLOITATION=" . $REX . " , PRODUITS_FINANCIERS=" . $PRODUITS_FINANCIERS . 
					" , CHARGES_FINANCIERES=" . $CHARGES_FINANCIERES . " , RECLASSEMENT_CREDIT_BAIL_FIN=" . $RECLASSEMENT_CREDIT_BAIL_FIN . " , RESULTAT_FINANCIER=" . $RFINANCIER . " , RESULTAT_COURANT_AVANT_IS=" . $RESULTAT_COURANT_AVANT_IS . 
					" , RESULTAT_EXCEPTIONNEL=" . $RESULTAT_EXCEPTIONNEL . " , PARTICIPATION_SALARIE=" . $PARTICIPATION_SALARIES . " , IMPOT_SOCIETE=" . $IS . " , RESULTAT_NET=" . $RESULTAT_NET . 
					" , DOTATION_PROVISION_CARACTERE_RESERVE=" . $DOTATION_PROVISIONS_CARACTERE_RESERVES  . " , PLUS_VALUE_CESSION=" . $PLUS_VALUE_CESSION . " , CAF=" . $CAF ." , NOPAT=" . $NOPAT . " 
					WHERE ID_SOCIETE = " . $bilan['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $bilan['ANNEE_BILAN'] . "';";
				
				//echo "Mis à jour bilan ".  $bilan['ANNEE_BILAN'];
				$result_update_sig = exec_query($con, $query_update_sig);
			}
			else {
				$query_insert_sig = "INSERT INTO  SIG (ID_SOCIETE, ANNEE_BILAN, VENTE_MARCHANDISE, COUT_ACHAT_MARCHANDISE,	MARGE_COMMERCIALE, PRODUCTION_VENDUE, PRODUCTION_STOCKEE, PRODUCTION_IMMOBILISEE, PRODUCTION, CONSOMMATION_MATIERE_PREMIERE, MARGE_BRUTE, AUTRE_ACHAT_CHARGE_EXTERNE, CORRECTION, VALEUR_AJOUTEE, SUBVENTION_EXPLOITATION, FRAIS_PERSONNEL, RECLASSEMENT_INTERIM, IMPOTS_TAXE, EBE, AUTRE_PRODUIT, AUTRE_CHARGE, DOTATION_AMORTISSEMENT, RECLASSEMENT_CREDIT_BAIL, DOTATION_PROVISION_NETTE_REPRISE, RESULTAT_EXPLOITATION, PRODUITS_FINANCIERS, CHARGES_FINANCIERES, RECLASSEMENT_CREDIT_BAIL_FIN, RESULTAT_FINANCIER, RESULTAT_COURANT_AVANT_IS, RESULTAT_EXCEPTIONNEL, PARTICIPATION_SALARIE, IMPOT_SOCIETE, RESULTAT_NET, DOTATION_PROVISION_CARACTERE_RESERVE, PLUS_VALUE_CESSION, CAF, NOPAT) 
					VALUES (" . $bilan['ID_SOCIETE'] . ", '" . $bilan['ANNEE_BILAN'] . "', " . $VENTE_MARCHANDISE . ", " . $COUT_ACHAT_MARCHANDISES_VENDUES . ", "
					. $MARGE_COMMERCIALE . ", " . $PRODUCTION_VENDUE . ", " . $PRODUCTION_STOCKEE . ", " . $PRODUCTION_IMMOBILISEE . ", " . $PRODUCTION . ", " . $CONSOMMATION_MATIERE_PREMIERE . ", " . $MARGE_BRUTE
					 . ", " . $AUTRES_ACHATS_CHARGES_EXTERNES . ", " . $CORRECTIONS . ", " . $VA . ", " . $SUBVENTION_EXPLOITATION . ", " . $FRAIS_PERSIONNEL . ", " . $RECLASSEMENT_INTERIM . ", " . $IMPOTS_TAXES 
					 . ", " . $EBE . ", " . $AUTRES_PRODUITS . ", " . $AUTRES_CHARGES . ", " . $DOTATIONS_AMORTISSEMENTS . ", " . $RECLASSEMENT_CREDIT_BAIL . ", " . $DOTATION_PROVISIONS_NETTES_REPRISES
					 . ", " . $REX . ", " . $PRODUITS_FINANCIERS . ", " . $CHARGES_FINANCIERES . ", " . $RECLASSEMENT_CREDIT_BAIL_FIN . ", " . $RFINANCIER . ", " . $RESULTAT_COURANT_AVANT_IS . ", " . $RESULTAT_EXCEPTIONNEL
					 . ", " . $PARTICIPATION_SALARIES . ", " . $IS . ", " . $RESULTAT_NET . ", " . $DOTATION_PROVISIONS_CARACTERE_RESERVES . ", " . $PLUS_VALUE_CESSION . ", " . $CAF . ", " . $NOPAT . ");";
				//echo $query_insert_sig;	 
				//echo "Insert bilan " .  $bilan['ANNEE_BILAN'];
				$result_insert_sig = exec_query($con, $query_insert_sig);
			}
			mysqli_free_result($result_sig);
			bilan_fonctionnel($con, $bilan, $NOPAT);
		}
		
		mysqli_free_result($result);
	}
}

//Recalcule le bilan d'une société sous forme de bilan fonctionnel. L'enregistre ou le met à jour dans la table BILAN_FONCTIONNEL
function bilan_fonctionnel($con, $bilan, $NOPAT){
	$ID_SOCIETE = $bilan['ID_SOCIETE'];
	$ANNEE_BILAN = $bilan['ANNEE_BILAN'];
	
	$CAPITAL_SOCIAL = $bilan['CAPITAL_SOCIAL'];
	$RESERVES_ET_RESULTATS = $bilan['RESERVE_LEGALE'] + $bilan['RESERVE_STATUTAIRE'] + $bilan['RESERVE_REGLEMENTEE'] + $bilan['AUTRES_RESERVES'] + $bilan['REPORT_A_NOUVEAU'] + $bilan['RESULTAT_EXERCICE'];
	$TOTAL_CAPITAUX_PROPRES = $CAPITAL_SOCIAL + $RESERVES_ET_RESULTATS ;
	$EMPRUNT_LMT_CREDIT_BAIL = $bilan['EMPRUNT_DETTE_ETABLISSEMENT_CREDIT'] + $bilan['EMPRUNT_DETTE_FINANCIERE_DIVERS'] - $bilan['DONT_CONCOURS_BANCAIRE_COURANT'] + $bilan['ENGAGEMENT_CREDIT_BAIL_MOBILIER']*0.75 + $bilan['ENGAGEMENT_CREDIT_BAIL_IMMOBILIER']*2/3;
	$PROVISIONS_RISQUES_CHARGES = $bilan['PROVISION_RISQUE'] + $bilan['PROVISION_CHARGE'];
	$TOTAL_DETTES_LMT = $EMPRUNT_LMT_CREDIT_BAIL + $PROVISIONS_RISQUES_CHARGES;
	$CAPITAUX_PERMANENTS = $TOTAL_CAPITAUX_PROPRES + $TOTAL_DETTES_LMT;
	$IMMO_INCORPORELLES = $bilan['FRAIS_ETABLISSEMENT'] - $bilan['FRAIS_ETABLISSEMENT_AMORTISSEMENT_PROVISIONS'] + $bilan['FRAIS_DEVELOPPEMENT'] - $bilan['FRAIS_DEVELOPPEMENT_AMORTISSEMENT_PROVISIONS']
	+ $bilan['CONCESSION_BREVET'] - $bilan['CONCESSION_BREVET_AMORTISSEMENT_PROVISIONS'] + $bilan['FOND_COMMERCIAL'] - $bilan['FOND_COMMERCIAL_AMORTISSEMENT_PROVISIONS'] + $bilan['AUTRES_IMMO_INCORPORELLES'] - $bilan['AUTRES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS']
	+ $bilan['AVANCES_ACOMPTES_IMMO_INCORPORELLES'] - $bilan['AVANCES_ACOMPTES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS']  + $bilan['ENGAGEMENT_CREDIT_BAIL_IMMOBILIER']*2/3;
	$IMMO_CORPORELLES = $bilan['TERRAIN'] - $bilan['TERRAIN_AMORTISSEMENT_PROVISIONS'] + $bilan['CONSTRUCTION'] - $bilan['CONSTRUCTION_AMORTISSEMENT_PROVISIONS'] + $bilan['INSTALLATIONS_TECHNIQUES'] - $bilan['INSTALLATIONS_TECHNIQUES_AMORTISSEMENT_PROVISIONS']
	+ $bilan['AUTRES_IMMO_CORPORELLES'] - $bilan['AUTRES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS'] + $bilan['IMMO_ENCOURS'] - $bilan['IMMO_ENCOURS_AMORTISSEMENT_PROVISIONS'] + $bilan['AVANCES_ACOMPTES_IMMO_CORPORELLES'] - $bilan['AVANCES_ACOMPTES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS'] + $bilan['ENGAGEMENT_CREDIT_BAIL_MOBILIER']*0.75;
	$IMMO_FINANCIERES =  $bilan['PARTICIPATION'] - $bilan['PARTICIPATION_AMORTISSEMENT_PROVISIONS'] + $bilan['AUTRES_PARTICIPATIONS'] - $bilan['AUTRES_PARTICIPATIONS_AMORTISSEMENT_PROVISIONS'] + $bilan['CREATIONS_RATTACHEES_PARTICIPATION'] - $bilan['CREATIONS_RATTACHEES_PARTICIPATION_AMORTISSEMENT_PROVISIONS']
	+ $bilan['AUTRES_TITRES_IMMOBILISES'] - $bilan['AUTRES_TITRES_IMMOBILISES_AMORTISSEMENT_PROVISIONS'] + $bilan['PRETS'] - $bilan['PRETS_AMORTISSEMENT_PROVISIONS'] + $bilan['AUTRES_IMMOBILISATIONS_FINANCIERES'] - $bilan['AUTRES_IMMOBILISATIONS_FINANCIERES_AMORTISSEMENT_PROVISIONS'];
	$IMMO = $IMMO_INCORPORELLES + $IMMO_CORPORELLES + $IMMO_FINANCIERES;
	$FR = $CAPITAUX_PERMANENTS - $IMMO;
	$STOCKS = $bilan['MATIERE_PREMIERE_APPROVISIONNEMENT'] - $bilan['MATIERE_PREMIERE_APPROVISIONNEMENT_AMORTISSEMENT_PROVISIONS'] + $bilan['EN_COURS_PRODUCTION_BIENS'] - $bilan['EN_COURS_PRODUCTION_BIENS_AMORTISSEMENT_PROVISIONS']
	+ $bilan['EN_COURS_PRODUCTION_SERVICES'] - $bilan['EN_COURS_PRODUCTION_SERVICES_AMORTISSEMENT_PROVISIONS'] + $bilan['PRODUITS_INTERMEDIAIRE_FINI'] - $bilan['PRODUITS_INTERMEDIAIRE_FINI_AMORTISSEMENT_PROVISIONS'] + $bilan['MARCHANDISE'] - $bilan['MARCHANDISE_AMORTISSEMENT_PROVISIONS'];
	$CLIENTS_AFFACTURAGE = $bilan['AVANCES_ACOMPTES_VERSES_COMMANDE'] - $bilan['AVANCES_ACOMPTES_VERSES_COMMANDE_AMORTISSEMENT_PROVISIONS'] + $bilan['CLIENTS_COMPTES_RATTACHES'] - $bilan['CLIENTS_COMPTES_RATTACHES_AMORTISSEMENT_PROVISIONS'] + $bilan['ENCOURS_AFFACTURAGE'];
	$AUTRES_CREANCES_EXPLOITATION = $bilan['AUTRES_CREANCES'] - $bilan['AUTRES_CREANCES_AMORTISSEMENT_PROVISIONS'] + $bilan['CHARGES_CONSTATEES_AVANCE'] - $bilan['CHARGES_CONSTATEES_AVANCE_AMORTISSEMENT_PROVISIONS'];
	$ACTIFS_CIRCULANTS_EXPLOITATION = $STOCKS + $CLIENTS_AFFACTURAGE + $AUTRES_CREANCES_EXPLOITATION;
	$FOURNISSEURS = $bilan['DETTE_FOURNISSEUR'];
	$AUTRES_DETTES_EXPLOITATION = $bilan['AVANCE_ACOMPTE_RECU_COMMANDE_EN_COURS'] + $bilan['DETTE_FISCALE_SOCIALE'] + $bilan['DETTE_IMMO'] + $bilan['AUTRES_DETTES'];
	$DETTES_EXPLOITATION = $FOURNISSEURS  + $AUTRES_DETTES_EXPLOITATION;
	$BFR = $ACTIFS_CIRCULANTS_EXPLOITATION - $DETTES_EXPLOITATION;
	$TRESORERIE_NETTE = $FR - $BFR;
	$DISPONIBILITES_VMP = $bilan['VALEUR_MOBILIERE_PLACEMENT'] - $bilan['VALEUR_MOBILIERE_PLACEMENT_AMORTISSEMENT_PROVISIONS'] + $bilan['DISPONIBILITES'] - $bilan['DISPONIBILITES_AMORTISSEMENT_PROVISIONS'];
	$CONCOURS_BANCAIRES_COURANTS = $bilan['DONT_CONCOURS_BANCAIRE_COURANT'];
	$ENCOURS_FINANCEMENT_AFFACTURAGE = $bilan['ENCOURS_AFFACTURAGE'];
	if($BFR>0)
		$CAPITAUX_EMPLOYES = $IMMO + $BFR;
	else
		$CAPITAUX_EMPLOYES = $IMMO;
	$ROCE = $NOPAT/$CAPITAUX_EMPLOYES;

	$query_bilan_fonctionnel = "SELECT ID_SOCIETE, ANNEE_BILAN FROM BILAN_FONCTIONNEL WHERE ID_SOCIETE = " . $bilan['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $bilan['ANNEE_BILAN'] . "'";
	$result_bilan_fonctionnel = exec_query($con, $query_bilan_fonctionnel);
	if(next_object($result_bilan_fonctionnel)) {
		$query_update_bilan_fonctionnel = "UPDATE BILAN_FONCTIONNEL SET CAPITAL_SOCIAL=" . $CAPITAL_SOCIAL . ", RESERVES_ET_RESULTATS=" . $RESERVES_ET_RESULTATS . ", TOTAL_CAPITAUX_PROPRES=" . $TOTAL_CAPITAUX_PROPRES . 
		", EMPRUNT_LMT_CREDIT_BAIL=" . $EMPRUNT_LMT_CREDIT_BAIL . ", PROVISIONS_RISQUES_CHARGES=" . $PROVISIONS_RISQUES_CHARGES . ", TOTAL_DETTES_LMT=" . $TOTAL_DETTES_LMT . ", CAPITAUX_PERMANENTS=" . $CAPITAUX_PERMANENTS . 
		", IMMO_INCORPORELLES=" . $IMMO_INCORPORELLES . ", IMMO_CORPORELLES=" . $IMMO_CORPORELLES . ", IMMO_FINANCIERES=" . $IMMO_FINANCIERES . ", IMMO=" . $IMMO . ", FOND_ROULEMENT=" . $FR . ", STOCKS=" . $STOCKS . 
		", CLIENTS_AFFACTURAGE=" . $CLIENTS_AFFACTURAGE . ", AUTRES_CREANCES_EXPLOITATION=" . $AUTRES_CREANCES_EXPLOITATION . ", ACTIFS_CIRCULANTS_EXPLOITATION=" . $ACTIFS_CIRCULANTS_EXPLOITATION . ", FOURNISSEURS=" . $FOURNISSEURS . 
		", AUTRES_DETTES_EXPLOITATION=" . $AUTRES_DETTES_EXPLOITATION . ", DETTES_EXPLOITATION=" . $DETTES_EXPLOITATION . ", BESOIN_FOND_ROULEMENT=" . $BFR . ", 	TRESORERIE_NETTE=" . $TRESORERIE_NETTE . 
		", DISPONIBILITES_VMP=" . $DISPONIBILITES_VMP . ", CONCOURS_BANCAIRES_COURANTS=" . $CONCOURS_BANCAIRES_COURANTS . ", ENCOURS_FINANCEMENT_AFFACTURAGE=" . $ENCOURS_FINANCEMENT_AFFACTURAGE . ", CAPITAUX_EMPLOYES=" . $CAPITAUX_EMPLOYES . ", ROCE=" . $ROCE . 
		" WHERE ID_SOCIETE = " . $bilan['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $bilan['ANNEE_BILAN'] . "'"; 
		
		$result_update_bilan_fonctionnel = exec_query($con, $query_update_bilan_fonctionnel);
//		echo $query_update_bilan_fonctionnel . "<BR><BR>";
	}
	else {
		$query_insert_bilan_fonctionnel = 	"INSERT INTO BILAN_FONCTIONNEL (ID_SOCIETE, ANNEE_BILAN, CAPITAL_SOCIAL, RESERVES_ET_RESULTATS, TOTAL_CAPITAUX_PROPRES, EMPRUNT_LMT_CREDIT_BAIL, PROVISIONS_RISQUES_CHARGES, TOTAL_DETTES_LMT, CAPITAUX_PERMANENTS, IMMO_INCORPORELLES, IMMO_CORPORELLES, IMMO_FINANCIERES, IMMO, FOND_ROULEMENT, STOCKS, CLIENTS_AFFACTURAGE, AUTRES_CREANCES_EXPLOITATION, ACTIFS_CIRCULANTS_EXPLOITATION, FOURNISSEURS, AUTRES_DETTES_EXPLOITATION, DETTES_EXPLOITATION, BESOIN_FOND_ROULEMENT, TRESORERIE_NETTE, DISPONIBILITES_VMP, CONCOURS_BANCAIRES_COURANTS, ENCOURS_FINANCEMENT_AFFACTURAGE, CAPITAUX_EMPLOYES, ROCE) VALUES 
		 (" . $bilan['ID_SOCIETE'] . ", '" . $bilan['ANNEE_BILAN'] . "', " . $CAPITAL_SOCIAL . ", " . $RESERVES_ET_RESULTATS . ", " . $TOTAL_CAPITAUX_PROPRES . ", " . $EMPRUNT_LMT_CREDIT_BAIL . ", " . $PROVISIONS_RISQUES_CHARGES . 
		 ", " . $TOTAL_DETTES_LMT . ", " . $CAPITAUX_PERMANENTS . ", " . $IMMO_INCORPORELLES . ", " . $IMMO_CORPORELLES . ", " . $IMMO_FINANCIERES . ", " . $IMMO . ", " . $FR . ", " . $STOCKS . ", " . $CLIENTS_AFFACTURAGE . 
		 ", " . $AUTRES_CREANCES_EXPLOITATION . ", " . $ACTIFS_CIRCULANTS_EXPLOITATION . ", " . $FOURNISSEURS . ", " . $AUTRES_DETTES_EXPLOITATION . ", " . $DETTES_EXPLOITATION . ", " . $BFR . ", " . $TRESORERIE_NETTE . 
		 ", " . $DISPONIBILITES_VMP . ", " . $CONCOURS_BANCAIRES_COURANTS . ", " .  $ENCOURS_FINANCEMENT_AFFACTURAGE. ", " . $CAPITAUX_EMPLOYES . ", " . $ROCE . ")";
//echo $query_insert_bilan_fonctionnel . "<BR><BR>";
		 $result_insert_bilan_fonctionnel = exec_query($con, $query_insert_bilan_fonctionnel);	
		
	}
	mysqli_free_result($result_bilan_fonctionnel);
}

// Calcule les ratios
function ratios($con, $id_societe){
	$query = "SELECT B.ID_SOCIETE AS ID_SOCIETE, B.ANNEE_BILAN AS ANNEE_BILAN,  FRAIS_ETABLISSEMENT, FRAIS_ETABLISSEMENT_AMORTISSEMENT_PROVISIONS, FRAIS_DEVELOPPEMENT, FRAIS_DEVELOPPEMENT_AMORTISSEMENT_PROVISIONS, CONCESSION_BREVET, CONCESSION_BREVET_AMORTISSEMENT_PROVISIONS, FOND_COMMERCIAL, FOND_COMMERCIAL_AMORTISSEMENT_PROVISIONS, AUTRES_IMMO_INCORPORELLES, AUTRES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS, AVANCES_ACOMPTES_IMMO_INCORPORELLES, AVANCES_ACOMPTES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS, TERRAIN, TERRAIN_AMORTISSEMENT_PROVISIONS, CONSTRUCTION, CONSTRUCTION_AMORTISSEMENT_PROVISIONS, INSTALLATIONS_TECHNIQUES, INSTALLATIONS_TECHNIQUES_AMORTISSEMENT_PROVISIONS, AUTRES_IMMO_CORPORELLES, AUTRES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS, IMMO_ENCOURS, IMMO_ENCOURS_AMORTISSEMENT_PROVISIONS, AVANCES_ACOMPTES_IMMO_CORPORELLES, AVANCES_ACOMPTES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS, PARTICIPATION, PARTICIPATION_AMORTISSEMENT_PROVISIONS, AUTRES_PARTICIPATIONS, AUTRES_PARTICIPATIONS_AMORTISSEMENT_PROVISIONS, CREATIONS_RATTACHEES_PARTICIPATION, CREATIONS_RATTACHEES_PARTICIPATION_AMORTISSEMENT_PROVISIONS, AUTRES_TITRES_IMMOBILISES, AUTRES_TITRES_IMMOBILISES_AMORTISSEMENT_PROVISIONS, PRETS, PRETS_AMORTISSEMENT_PROVISIONS, AUTRES_IMMOBILISATIONS_FINANCIERES, AUTRES_IMMOBILISATIONS_FINANCIERES_AMORTISSEMENT_PROVISIONS, MATIERE_PREMIERE_APPROVISIONNEMENT, MATIERE_PREMIERE_APPROVISIONNEMENT_AMORTISSEMENT_PROVISIONS, MARCHANDISE, MARCHANDISE_AMORTISSEMENT_PROVISIONS, CLIENTS_COMPTES_RATTACHES, CLIENTS_COMPTES_RATTACHES_AMORTISSEMENT_PROVISIONS, ACHAT_MARCHANDISES, ACHAT_MATIERE_PREMIERE, B.AUTRE_ACHAT_CHARGE_EXTERNE AS AUTRE_ACHAT_CHARGE_EXTERNE, LOCATION, TVA_COLLECTEE, TVA_DEDUCTIBLE, EFFECTIF_MOYEN, 
	VENTE_MARCHANDISE, COUT_ACHAT_MARCHANDISE, MARGE_COMMERCIALE, PRODUCTION_VENDUE, S.PRODUCTION_STOCKEE AS PRODUCTION_STOCKEE, S.PRODUCTION_IMMOBILISEE AS PRODUCTION_IMMOBILISEE, PRODUCTION, CONSOMMATION_MATIERE_PREMIERE, MARGE_BRUTE, S.AUTRE_ACHAT_CHARGE_EXTERNE AS AUTRE_ACHAT_CHARGE_EXTERNE_SIG, CORRECTION, VALEUR_AJOUTEE, S.SUBVENTION_EXPLOITATION AS SUBVENTION_EXPLOITATION, FRAIS_PERSONNEL, RECLASSEMENT_INTERIM, IMPOTS_TAXE, EBE, S.AUTRE_PRODUIT AS AUTRE_PRODUIT, S.AUTRE_CHARGE AS AUTRE_CHARGE, DOTATION_AMORTISSEMENT, RECLASSEMENT_CREDIT_BAIL, DOTATION_PROVISION_NETTE_REPRISE, RESULTAT_EXPLOITATION, PRODUITS_FINANCIERS, CHARGES_FINANCIERES, RECLASSEMENT_CREDIT_BAIL_FIN, RESULTAT_FINANCIER, RESULTAT_COURANT_AVANT_IS, RESULTAT_EXCEPTIONNEL, S.PARTICIPATION_SALARIE AS PARTICIPATION_SALARIE, IMPOT_SOCIETE, RESULTAT_NET, DOTATION_PROVISION_CARACTERE_RESERVE, PLUS_VALUE_CESSION, CAF, NOPAT, 
	BF.CAPITAL_SOCIAL AS CAPITAL_SOCIAL, RESERVES_ET_RESULTATS, TOTAL_CAPITAUX_PROPRES, EMPRUNT_LMT_CREDIT_BAIL, PROVISIONS_RISQUES_CHARGES, TOTAL_DETTES_LMT, CAPITAUX_PERMANENTS, IMMO_INCORPORELLES, IMMO_CORPORELLES, IMMO_FINANCIERES, IMMO, FOND_ROULEMENT, STOCKS, CLIENTS_AFFACTURAGE, AUTRES_CREANCES_EXPLOITATION, ACTIFS_CIRCULANTS_EXPLOITATION, FOURNISSEURS, AUTRES_DETTES_EXPLOITATION, DETTES_EXPLOITATION, BESOIN_FOND_ROULEMENT, TRESORERIE_NETTE, DISPONIBILITES_VMP, CONCOURS_BANCAIRES_COURANTS, ENCOURS_FINANCEMENT_AFFACTURAGE, CAPITAUX_EMPLOYES, ROCE
	FROM BILAN B, SIG S, BILAN_FONCTIONNEL BF 
	WHERE B.ID_SOCIETE=S.ID_SOCIETE AND B.ID_SOCIETE=BF.ID_SOCIETE AND B.ANNEE_BILAN=S.ANNEE_BILAN AND B.ANNEE_BILAN=BF.ANNEE_BILAN
	AND B.ID_SOCIETE=" . $id_societe . " 
	ORDER BY ANNEE_BILAN DESC	";
	
	$result = exec_query($con, $query);	
	if(false != $result) {
		while($ratios = next_line($result)){
			$ACHAT_HT_ESTIME = $ratios['COUT_ACHAT_MARCHANDISE'] + $ratios['CONSOMMATION_MATIERE_PREMIERE'] + $ratios['AUTRE_ACHAT_CHARGE_EXTERNE'];
			$VENTE_HT_ESTIME = $ratios['VENTE_MARCHANDISE'] + $ratios['PRODUCTION_VENDUE'];
			$TAUX_TVA_VENTE = $ratios['TVA_COLLECTEE']/$VENTE_HT_ESTIME ;
			$TAUX_TVA_ACHAT = $ratios['TVA_DEDUCTIBLE']/$ACHAT_HT_ESTIME;
			$TAUX_MARGE_BRUTE = $ratios['MARGE_BRUTE']/$VENTE_HT_ESTIME;
			$TAUX_IMPOTS_VA = ($ratios['IMPOTS_TAXE']+$ratios['IMPOT_SOCIETE'])/$ratios['VALEUR_AJOUTEE'];
			$TAUX_CHARGES_EXT_CA = ($ratios['AUTRE_ACHAT_CHARGE_EXTERNE_SIG']+$ratios['CORRECTION'])/$VENTE_HT_ESTIME;
			$TAUX_LOC_IMMO_CA = $ratios['LOCATION']/$VENTE_HT_ESTIME;
			$TAUX_INTERET_FIN_VA = $ratios['CHARGES_FINANCIERES']/$ratios['VALEUR_AJOUTEE'];
			$TAUX_CHARGE_PERSONNEL_CA = ($ratios['FRAIS_PERSONNEL']+$ratios['RECLASSEMENT_INTERIM'])/$VENTE_HT_ESTIME;
			$TAUX_CHARGE_PERSONNEL_VA = ($ratios['FRAIS_PERSONNEL']+$ratios['RECLASSEMENT_INTERIM'])/$ratios['VALEUR_AJOUTEE'];
			$TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN = $ratios['FRAIS_PERSONNEL']/$ratios['EFFECTIF_MOYEN'];
			$TAUX_CA_EFFECTIF_MOYEN = $VENTE_HT_ESTIME/$ratios['EFFECTIF_MOYEN'];
			$TAUX_MARGE_EFFECTIF_MOYEN = $ratios['MARGE_BRUTE']/$ratios['EFFECTIF_MOYEN'];
			$TAUX_RESULTAT_CA = $ratios['RESULTAT_EXPLOITATION']/$VENTE_HT_ESTIME;
			$TAUX_EBE_CA = $ratios['EBE']/$VENTE_HT_ESTIME;
			$TAUX_RESULTAT_NET_CA = $ratios['RESULTAT_NET']/$VENTE_HT_ESTIME;
			$TAUX_CAF_CA = $ratios['CAF']/$VENTE_HT_ESTIME;
			$TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET = $ratios['RESULTAT_NET']/($ratios['TOTAL_CAPITAUX_PROPRES']-$ratios['RESULTAT_NET']);
			$TAUX_CAPITAUX_PROPRES_DLMT = $ratios['TOTAL_CAPITAUX_PROPRES']/$ratios['TOTAL_DETTES_LMT'];
			$TAUX_DETTES_FINANCIERES_CAF = $ratios['TOTAL_DETTES_LMT']/$ratios['CAF'];
			$TAUX_DISPO_VMP_PASSIF_CT = $ratios['DISPONIBILITES_VMP']/$ratios['DETTES_EXPLOITATION'];
			$TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT = ($ratios['ACTIFS_CIRCULANTS_EXPLOITATION']-$ratios['STOCKS']+$ratios['DISPONIBILITES_VMP'])/($ratios['DETTES_EXPLOITATION']-$ratios['CONCOURS_BANCAIRES_COURANTS']);
			$TAUX_ACTIF_CIRCULANT_PASSIF_CT = ($ratios['ACTIFS_CIRCULANTS_EXPLOITATION']+$ratios['DISPONIBILITES_VMP'])/($ratios['DETTES_EXPLOITATION']-$ratios['CONCOURS_BANCAIRES_COURANTS']);
			$TAUX_BFR_CA = $ratios['BESOIN_FOND_ROULEMENT']*365/$VENTE_HT_ESTIME;
			$TAUX_STOCK_FINAL_ACHAT_MARCHANDISES = ($ratios['MATIERE_PREMIERE_APPROVISIONNEMENT']+$ratios['MARCHANDISE'])*365/($ratios['ACHAT_MARCHANDISES']+$ratios['ACHAT_MATIERE_PREMIERE']);
			$TAUX_CREANCES_CLIENTS_CA = $ratios['CLIENTS_COMPTES_RATTACHES']*365/($VENTE_HT_ESTIME*(1+$TAUX_TVA_VENTE));
			$TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT = $ratios['FOURNISSEURS']*365/($ratios['ACHAT_MARCHANDISES']+$ratios['ACHAT_MATIERE_PREMIERE']+$ratios['AUTRE_ACHAT_CHARGE_EXTERNE']);
			$TAUX_AMMO_IMMO = ($ratios['FRAIS_ETABLISSEMENT_AMORTISSEMENT_PROVISIONS']+$ratios['FRAIS_DEVELOPPEMENT_AMORTISSEMENT_PROVISIONS']+$ratios['CONCESSION_BREVET_AMORTISSEMENT_PROVISIONS']+$ratios['FOND_COMMERCIAL_AMORTISSEMENT_PROVISIONS']+$ratios['AUTRES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS']+$ratios['AVANCES_ACOMPTES_IMMO_INCORPORELLES_AMORTISSEMENT_PROVISIONS']+$ratios['TERRAIN_AMORTISSEMENT_PROVISIONS']+$ratios['CONSTRUCTION_AMORTISSEMENT_PROVISIONS']+$ratios['INSTALLATIONS_TECHNIQUES_AMORTISSEMENT_PROVISIONS']+$ratios['AUTRES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS']+$ratios['IMMO_ENCOURS_AMORTISSEMENT_PROVISIONS']+$ratios['AVANCES_ACOMPTES_IMMO_CORPORELLES_AMORTISSEMENT_PROVISIONS']+$ratios['PARTICIPATION_AMORTISSEMENT_PROVISIONS']+$ratios['AUTRES_PARTICIPATIONS_AMORTISSEMENT_PROVISIONS']+$ratios['CREATIONS_RATTACHEES_PARTICIPATION_AMORTISSEMENT_PROVISIONS']+$ratios['AUTRES_TITRES_IMMOBILISES_AMORTISSEMENT_PROVISIONS']+$ratios['PRETS_AMORTISSEMENT_PROVISIONS']+$ratios['AUTRES_IMMOBILISATIONS_FINANCIERES_AMORTISSEMENT_PROVISIONS']			)/($ratios['FRAIS_ETABLISSEMENT']+$ratios['FRAIS_DEVELOPPEMENT']+$ratios['CONCESSION_BREVET']+$ratios['FOND_COMMERCIAL']+$ratios['AUTRES_IMMO_INCORPORELLES']+$ratios['AVANCES_ACOMPTES_IMMO_INCORPORELLES']+$ratios['TERRAIN']+$ratios['CONSTRUCTION']+$ratios['INSTALLATIONS_TECHNIQUES']+$ratios['AUTRES_IMMO_CORPORELLES']+$ratios['IMMO_ENCOURS']+$ratios['AVANCES_ACOMPTES_IMMO_CORPORELLES']+$ratios['PARTICIPATION']+$ratios['AUTRES_PARTICIPATIONS']+$ratios['CREATIONS_RATTACHEES_PARTICIPATION']+$ratios['AUTRES_TITRES_IMMOBILISES']+$ratios['PRETS']+$ratios['AUTRES_IMMOBILISATIONS_FINANCIERES']);
			$TAUX_INTERETS_ENDETTEMENT= $ratios['CHARGES_FINANCIERES']/($ratios['EMPRUNT_LMT_CREDIT_BAIL']+$ratios['CONCOURS_BANCAIRES_COURANTS']);
			$TAUX_INTERETS_CA = $ratios['CHARGES_FINANCIERES']/$VENTE_HT_ESTIME;
			$TAUX_NOPAT_CA = $ratios['NOPAT']/$VENTE_HT_ESTIME;
			$TAUX_CA_CE = $VENTE_HT_ESTIME/$ratios['CAPITAUX_EMPLOYES'];
			$TAUX_ROCE = $TAUX_CA_CE*$TAUX_NOPAT_CA;
			$TAUX_ROE = $ratios['RESULTAT_NET']/$ratios['TOTAL_CAPITAUX_PROPRES'];
			$TAUX_FRAIS_FINANCIERS = $ratios['CHARGES_FINANCIERES']*(1-$ratios['IMPOT_SOCIETE']/$ratios['RESULTAT_COURANT_AVANT_IS'])/$ratios['NOPAT'];
			
			$TAUX_RBT_CAPITAL = 0;//$ratios[''];
			$FLUX_TRESORERIE_ACTIONNAIRES = 0;//$ratios[''];
			$CHARGES_VARIABLES = 0;//$ratios[''];
			$TAUX_MARGE_COUT_VARIABLE = 0;//$ratios[''];
			$CHARGES_FIXES = 0;//$ratios[''];
			$SEUIL_RENTABILITE = 0;//$ratios[''];
			$TCCE = 0;//$ratios[''];
			$FCF =0;// $ratios[''];
			
			$query_ratios = "SELECT ID_SOCIETE, ANNEE_BILAN FROM RATIOS WHERE ID_SOCIETE = " . $ratios['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $ratios['ANNEE_BILAN'] . "'";
			$result_ratios = exec_query($con, $query_ratios);
			if(next_object($result_ratios)){
				$query_update_ratios= "UPDATE RATIOS SET 
				ACHAT_HT_ESTIME= " . $ACHAT_HT_ESTIME . ",VENTE_HT_ESTIME= " . $VENTE_HT_ESTIME . ",TAUX_TVA_VENTE= " . $TAUX_TVA_VENTE . ",TAUX_TVA_ACHAT= " . $TAUX_TVA_ACHAT . ",TAUX_MARGE_BRUTE= " . $TAUX_MARGE_BRUTE . ",TAUX_IMPOTS_VA= " . $TAUX_IMPOTS_VA . ",TAUX_CHARGES_EXT_CA= " . $TAUX_CHARGES_EXT_CA . 
				", TAUX_LOC_IMMO_CA= " . $TAUX_LOC_IMMO_CA . ",TAUX_INTERET_FIN_VA= " . $TAUX_INTERET_FIN_VA . ",TAUX_CHARGE_PERSONNEL_CA= " . $TAUX_CHARGE_PERSONNEL_CA . ",TAUX_CHARGE_PERSONNEL_VA= " . $TAUX_CHARGE_PERSONNEL_VA . ",TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN= " . $TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN . 
				",TAUX_CA_EFFECTIF_MOYEN= " . $TAUX_CA_EFFECTIF_MOYEN . ",TAUX_MARGE_EFFECTIF_MOYEN= " . $TAUX_MARGE_EFFECTIF_MOYEN . ",TAUX_RESULTAT_CA= " . $TAUX_RESULTAT_CA . ",TAUX_EBE_CA= " . $TAUX_EBE_CA . ",TAUX_RESULTAT_NET_CA= " . $TAUX_RESULTAT_NET_CA . ",TAUX_CAF_CA= " . $TAUX_CAF_CA . 
				",TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET= " . $TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET . ",TAUX_CAPITAUX_PROPRES_DLMT= " . $TAUX_CAPITAUX_PROPRES_DLMT . ",TAUX_DETTES_FINANCIERES_CAF= " . $TAUX_DETTES_FINANCIERES_CAF . ",TAUX_DISPO_VMP_PASSIF_CT= " . $TAUX_DISPO_VMP_PASSIF_CT . 
				",TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT= " . $TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT . ",TAUX_ACTIF_CIRCULANT_PASSIF_CT= " . $TAUX_ACTIF_CIRCULANT_PASSIF_CT . ",TAUX_BFR_CA= " . $TAUX_BFR_CA . ",TAUX_STOCK_FINAL_ACHAT_MARCHANDISES= " . $TAUX_STOCK_FINAL_ACHAT_MARCHANDISES . ",TAUX_CREANCES_CLIENTS_CA= " . $TAUX_CREANCES_CLIENTS_CA . ",TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT= " . $TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT . 
				",TAUX_AMMO_IMMO= " . $TAUX_AMMO_IMMO . ",TAUX_INTERETS_ENDETTEMENT= " . $TAUX_INTERETS_ENDETTEMENT . ",TAUX_INTERETS_CA= " . $TAUX_INTERETS_CA . ",TAUX_NOPAT_CA= " . $TAUX_NOPAT_CA . ",TAUX_CA_CE= " . $TAUX_CA_CE . ",TAUX_ROCE= " . $TAUX_ROCE . ",TAUX_ROE= " . $TAUX_ROE . ",TCCE= " . $TCCE . 
				",FCF= " . $FCF . ",TAUX_FRAIS_FINANCIERS= " . $TAUX_FRAIS_FINANCIERS . ",TAUX_RBT_CAPITAL= " . $TAUX_RBT_CAPITAL . ",FLUX_TRESORERIE_ACTIONNAIRES= " . $FLUX_TRESORERIE_ACTIONNAIRES . ",CHARGES_VARIABLES= " . $CHARGES_VARIABLES . ",TAUX_MARGE_COUT_VARIABLE= " . $TAUX_MARGE_COUT_VARIABLE . ",CHARGES_FIXES= " . $CHARGES_FIXES . 
				",SEUIL_RENTABILITE=" . $SEUIL_RENTABILITE . " 
				WHERE ID_SOCIETE = " . $ratios['ID_SOCIETE'] . " AND ANNEE_BILAN = '" . $ratios['ANNEE_BILAN'] . "'";
				$result_update_ratios = exec_query($con, $query_update_ratios);
			}
			else {
				$query_insert_ratios= "INSERT INTO RATIOS (ID_SOCIETE ,ANNEE_BILAN ,ACHAT_HT_ESTIME,VENTE_HT_ESTIME,TAUX_TVA_VENTE,TAUX_TVA_ACHAT,TAUX_MARGE_BRUTE,TAUX_IMPOTS_VA,TAUX_CHARGES_EXT_CA, TAUX_LOC_IMMO_CA,TAUX_INTERET_FIN_VA,TAUX_CHARGE_PERSONNEL_CA,TAUX_CHARGE_PERSONNEL_VA,TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN,TAUX_CA_EFFECTIF_MOYEN,TAUX_MARGE_EFFECTIF_MOYEN,TAUX_RESULTAT_CA,TAUX_EBE_CA,TAUX_RESULTAT_NET_CA,TAUX_CAF_CA,TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET,TAUX_CAPITAUX_PROPRES_DLMT,TAUX_DETTES_FINANCIERES_CAF,TAUX_DISPO_VMP_PASSIF_CT,TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT,TAUX_ACTIF_CIRCULANT_PASSIF_CT,TAUX_BFR_CA,TAUX_STOCK_FINAL_ACHAT_MARCHANDISES,TAUX_CREANCES_CLIENTS_CA,TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT,TAUX_AMMO_IMMO,TAUX_INTERETS_ENDETTEMENT,TAUX_INTERETS_CA,TAUX_NOPAT_CA,TAUX_CA_CE,TAUX_ROCE,TAUX_ROE,TCCE,FCF,TAUX_FRAIS_FINANCIERS,TAUX_RBT_CAPITAL,FLUX_TRESORERIE_ACTIONNAIRES,CHARGES_VARIABLES,TAUX_MARGE_COUT_VARIABLE,CHARGES_FIXES,SEUIL_RENTABILITE) VALUES 
				(" . $ratios['ID_SOCIETE'] . ", '" . $ratios['ANNEE_BILAN'] . "', " . $ACHAT_HT_ESTIME . ", " . $VENTE_HT_ESTIME . ", " . $TAUX_TVA_VENTE . ", " . $TAUX_TVA_ACHAT . ", " . $TAUX_MARGE_BRUTE . ", " . $TAUX_IMPOTS_VA . ", " . $TAUX_CHARGES_EXT_CA . ", " . $TAUX_LOC_IMMO_CA . ", " . $TAUX_INTERET_FIN_VA . ", " . $TAUX_CHARGE_PERSONNEL_CA . ", " . $TAUX_CHARGE_PERSONNEL_VA . ", " . $TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN . ", " . $TAUX_CA_EFFECTIF_MOYEN . ", " . $TAUX_MARGE_EFFECTIF_MOYEN . ", " . $TAUX_RESULTAT_CA . ", " . $TAUX_EBE_CA . ", " . $TAUX_RESULTAT_NET_CA . ", " . $TAUX_CAF_CA . ", " . $TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET . ", " . $TAUX_CAPITAUX_PROPRES_DLMT . ", " . $TAUX_DETTES_FINANCIERES_CAF . ", " . $TAUX_DISPO_VMP_PASSIF_CT . ", " . $TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT . ", " . $TAUX_ACTIF_CIRCULANT_PASSIF_CT . ", " . $TAUX_BFR_CA . ", " . $TAUX_STOCK_FINAL_ACHAT_MARCHANDISES . ", " . $TAUX_CREANCES_CLIENTS_CA . ", " . $TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT . ", " . $TAUX_AMMO_IMMO . ", " . $TAUX_INTERETS_ENDETTEMENT . ", " . $TAUX_INTERETS_CA . ", " . $TAUX_NOPAT_CA . ", " . $TAUX_CA_CE . ", " . $TAUX_ROCE . ", " . $TAUX_ROE . ", " . $TCCE . ", " . $FCF . ", " . $TAUX_FRAIS_FINANCIERS . ", " . $TAUX_RBT_CAPITAL . ", " . $FLUX_TRESORERIE_ACTIONNAIRES . ", " . $CHARGES_VARIABLES . ", " . $TAUX_MARGE_COUT_VARIABLE . ", " . $CHARGES_FIXES . ", " . $SEUIL_RENTABILITE . ")"; 
				echo $query_insert_ratios;
				$result_insert_ratios = exec_query($con, $query_insert_ratios);
			}
			mysqli_free_result($result_ratios);
		}
		mysqli_free_result($result);
	}
}


//Affiche le tableau des SIG pour une société donnée, ainsi que l'évolution d'une année sur l'autre
function tableau_sig($con, $id_societe,$annee_debut, $annee_fin){
	//$tableau_sig[];
	$query = "SELECT ID_SOCIETE, ANNEE_BILAN, VENTE_MARCHANDISE, COUT_ACHAT_MARCHANDISE, MARGE_COMMERCIALE, PRODUCTION_VENDUE, PRODUCTION_STOCKEE, PRODUCTION_IMMOBILISEE, PRODUCTION, CONSOMMATION_MATIERE_PREMIERE, 
	MARGE_BRUTE, AUTRE_ACHAT_CHARGE_EXTERNE, CORRECTION, VALEUR_AJOUTEE, SUBVENTION_EXPLOITATION, FRAIS_PERSONNEL, RECLASSEMENT_INTERIM, IMPOTS_TAXE, EBE, AUTRE_PRODUIT, AUTRE_CHARGE, DOTATION_AMORTISSEMENT, 
	RECLASSEMENT_CREDIT_BAIL, DOTATION_PROVISION_NETTE_REPRISE, RESULTAT_EXPLOITATION, PRODUITS_FINANCIERS, CHARGES_FINANCIERES, RECLASSEMENT_CREDIT_BAIL_FIN, RESULTAT_FINANCIER, RESULTAT_COURANT_AVANT_IS, 
	RESULTAT_EXCEPTIONNEL, PARTICIPATION_SALARIE, IMPOT_SOCIETE, RESULTAT_NET, DOTATION_PROVISION_CARACTERE_RESERVE, PLUS_VALUE_CESSION, CAF, NOPAT 
	FROM SIG WHERE ID_SOCIETE=" . $id_societe . " AND ANNEE_BILAN>= ". $annee_debut . " AND ANNEE_BILAN<=" . $annee_fin . " ORDER BY ANNEE_BILAN DESC";
	$result = exec_query($con, $query);
	while($sig = next_line($result)){
		$tableau_sig[] = $sig;
	}
	display_sig_head();
	for($i=0;$i<count($tableau_sig)-1; $i++){
		display_sig_detail($tableau_sig[$i], 0, '€');
		display_sig_growth($tableau_sig[$i], $tableau_sig[$i+1]);

	}
	display_sig_detail($tableau_sig[count($tableau_sig)-1], 0, '€');
	display_sig_end();
}


function tableau_bilan_fonctionnel($con, $id_societe){
	$query = "SELECT ID_SOCIETE, ANNEE_BILAN, CAPITAL_SOCIAL, RESERVES_ET_RESULTATS, TOTAL_CAPITAUX_PROPRES, EMPRUNT_LMT_CREDIT_BAIL, PROVISIONS_RISQUES_CHARGES, TOTAL_DETTES_LMT, CAPITAUX_PERMANENTS, IMMO_INCORPORELLES, IMMO_CORPORELLES, IMMO_FINANCIERES, IMMO, FOND_ROULEMENT, STOCKS, CLIENTS_AFFACTURAGE, AUTRES_CREANCES_EXPLOITATION, ACTIFS_CIRCULANTS_EXPLOITATION, FOURNISSEURS, AUTRES_DETTES_EXPLOITATION, DETTES_EXPLOITATION, BESOIN_FOND_ROULEMENT, TRESORERIE_NETTE, DISPONIBILITES_VMP, CONCOURS_BANCAIRES_COURANTS, ENCOURS_FINANCEMENT_AFFACTURAGE, CAPITAUX_EMPLOYES, ROCE 
	FROM BILAN_FONCTIONNEL WHERE ID_SOCIETE=" . $id_societe . " ORDER BY ANNEE_BILAN DESC";
	$result = exec_query($con, $query);
	display_bilan_fonctionnel_head();
	while($bilan_fonctionnel = next_line($result)){
		display_bilan_fonctionnel_detail($bilan_fonctionnel, 0, '€');
	}
	display_bilan_fonctionnel_end();
}

function tableau_ratios($con, $id_societe, $annee_debut, $annee_fin){
	$query = "SELECT ID_SOCIETE, ANNEE_BILAN, ACHAT_HT_ESTIME, VENTE_HT_ESTIME, TAUX_TVA_VENTE, TAUX_TVA_ACHAT, TAUX_MARGE_BRUTE, TAUX_IMPOTS_VA, TAUX_CHARGES_EXT_CA, TAUX_LOC_IMMO_CA, TAUX_INTERET_FIN_VA, TAUX_CHARGE_PERSONNEL_CA, TAUX_CHARGE_PERSONNEL_VA, TAUX_CHARGE_PERSONNEL_EFFECTIF_MOYEN, TAUX_CA_EFFECTIF_MOYEN, TAUX_MARGE_EFFECTIF_MOYEN, TAUX_RESULTAT_CA, TAUX_EBE_CA, TAUX_RESULTAT_NET_CA, TAUX_CAF_CA, TAUX_RESULTAT_NET_CAPITAUX_PROPRES_RESULTAT_NET, TAUX_CAPITAUX_PROPRES_DLMT, TAUX_DETTES_FINANCIERES_CAF, TAUX_DISPO_VMP_PASSIF_CT, TAUX_ACTIF_CIRCULANT_HORS_STOCK_PASSIF_CT, TAUX_ACTIF_CIRCULANT_PASSIF_CT, TAUX_BFR_CA, TAUX_STOCK_FINAL_ACHAT_MARCHANDISES, TAUX_CREANCES_CLIENTS_CA, TAUX_DETTES_FOURNISSEURS_ACHAT_MP_CHARGES_EXT, TAUX_AMMO_IMMO, TAUX_INTERETS_ENDETTEMENT, TAUX_INTERETS_CA, TAUX_NOPAT_CA, TAUX_CA_CE, TAUX_ROCE, TAUX_ROE, TCCE, FCF, TAUX_FRAIS_FINANCIERS, TAUX_RBT_CAPITAL, FLUX_TRESORERIE_ACTIONNAIRES, CHARGES_VARIABLES, TAUX_MARGE_COUT_VARIABLE, CHARGES_FIXES, SEUIL_RENTABILITE
	FROM RATIOS WHERE ID_SOCIETE=" . $id_societe . " AND ANNEE_BILAN>= ". $annee_debut . " AND ANNEE_BILAN<=" . $annee_fin . " ORDER BY ANNEE_BILAN DESC";
	$result = exec_query($con, $query);
	display_bilan_ratios_head();
	while($ratios = next_line($result)){
		display_ratios_detail($ratios);
	}
	display_ratios_end();
}
?>