INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("NONG", "Khai Phat", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("NONG", "Yu Lin", 0);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("TANG", "Caroline", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("NONG", "Philippe", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("VINETOT", "Serge", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("SANGARE", "Binta", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("KNAFO", "Elsa", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("YILMAZ", "Zeliha", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("SAINT-HILAIRE", "Jean-Junior", 0);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("GULNAZ", "Dondu", 1);
INSERT INTO SALARIE(NOM, PRENOM, ACTIF) VALUES ("GULNAZ", "Dondu", 1);

