INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (0, 'Comptant');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (7, '7 Jours');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (10, '10 Jours');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (15, '15 Jours');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (21, '21 Jours');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (30, '30 Jours date de facture');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (300, '30 Jours fin de mois');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (310, '30 Jours fin de décade');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (315, '30 Jours fin de quinzaine');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (45, '45 Jours');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (450, '45 Jours fin de mois');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (451, 'Fin de mois 45 Jours ');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (550, '55 Jours fin de décade');
INSERT INTO ECHEANCE (CODE_ECHEANCE, DESC_ECHEANCE) VALUES (60, '60 Jours date de facture');

