INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Serge',1);
INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Anna',1);
INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Caro',1);
INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Binta',1);
INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Elsa',1);
INSERT INTO SALESDEPT(SALESREP,ACTIF) VALUES('Zeliha',1);
