INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (1, 'LCR');
INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (2, 'Chèque');
INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (3, 'Prélèvement');
INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (4, 'Virement');
INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (5, 'CB');
INSERT INTO MODE_PAIEMENT (CODE_PAIEMENT, DESC_PAIEMENT) VALUES (6, 'Espèce');
