SELECT S.NOM AS NOM, S.PRENOM AS PRENOM, SUM(R.COUT_GLOBAL), YEAR(R.DATE_SALAIRE) AS YEAR FROM REMUNERATION R, SALARIE S WHERE S.ID_SALARIE=R.ID_SALARIE GROUP BY YEAR, S.ID_SALARIE ORDER BY NOM ASC, PRENOM ASC, YEAR DESC;


SELECT SUM(MONTANT_TTC), MONTH(F.DATE_FACTURE) AS F_MONTH, YEAR(F.DATE_FACTURE) AS F_YEAR, S.DESC_STATUT AS STATUT FROM FACTURES AS F 
	RIGHT OUTER JOIN REF_DATE AS D
		ON MONTH(F.DATE_FACTURE) = D.MONTH
			AND YEAR(F.DATE_FACTURE) = D.CIVIL_YEAR,
	STATUT_FACTURE S
WHERE 
F.CODE_STATUT = S.CODE_STATUT
GROUP BY F_MONTH, F_YEAR, STATUT



SELECT SUM(F.MONTANT_TTC), MONTH AS F_MONTH, CIVIL_YEAR AS F_YEAR, STATUT_FACTURE.CODE_STATUT AS STATUT 
FROM REF_DATE AS D 	
LEFT JOIN FACTURES AS F ON D.CIVIL_YEAR = YEAR(F.DATE_FACTURE) AND D.MONTH = MONTH(F.DATE_FACTURE) AND YEAR(F.DATE_FACTURE) = 2017 
RIGHT JOIN STATUT_FACTURE ON STATUT_FACTURE.CODE_STATUT = F.CODE_STATUT
GROUP BY D.FULL_DATE,  STATUT_FACTURE.CODE_STATUT




SELECT STATUT_FACTURE.DESC_STATUT, LF.TOTAL_TTC, LF.MONTH, LF.YEAR  FROM STATUT_FACTURE 
LEFT JOIN 
(
SELECT SUM(MONTANT_TTC) AS TOTAL_TTC, 
								MONTH, 
					CIVIL_YEAR AS YEAR, 
				F.CODE_STATUT AS STATUT,
				D.FULL_DATE AS FULL_DATE 
FROM REF_DATE AS D 
	LEFT OUTER JOIN FACTURES AS F 
		ON D.CIVIL_YEAR = YEAR(F.DATE_FACTURE) AND D.MONTH = MONTH(F.DATE_FACTURE) 
WHERE D.CIVIL_YEAR=2017 
GROUP BY FULL_DATE, STATUT
)  LF
ON STATUT_FACTURE.CODE_STATUT = LF.STATUT
GROUP BY STATUT_FACTURE.DESC_STATUT, LF.FULL_DATE



SELECT S.DESC_STATUT, S.CIVIL_YEAR AS YEAR, S.MONTH, SUM(MONTANT_TTC) AS TOTAL_TTC FROM 
(SELECT DESC_STATUT, CODE_STATUT, CIVIL_YEAR, MONTH, MONTANT_TTC, FULL_DATE FROM STATUT_FACTURE, REF_DATE WHERE CIVIL_YEAR=2017) S 
LEFT JOIN FACTURES F 
ON S.CIVIL_YEAR = YEAR(F.DATE_FACTURE) 
AND S.MONTH = MONTH(F.DATE_FACTURE) 
AND S.CODE_STATUT = F.CODE_STATUT 
GROUP BY S.FULL_DATE, S.DESC_STATUT ORDER BY S.CODE_STATUT, MONTH ASC