INSERT INTO NATURE_FACTURE (CODE_NATURE, DESC_NATURE) VALUES (1, 'Facture');
INSERT INTO NATURE_FACTURE (CODE_NATURE, DESC_NATURE) VALUES (2, 'Avoir');
INSERT INTO NATURE_FACTURE (CODE_NATURE, DESC_NATURE) VALUES (3, 'RFA');
INSERT INTO NATURE_FACTURE (CODE_NATURE, DESC_NATURE) VALUES (4, 'Prestation');
