INSERT INTO STATUT_FACTURE (CODE_STATUT, DESC_STATUT) VALUES (1, 'Saisie');
INSERT INTO STATUT_FACTURE (CODE_STATUT, DESC_STATUT) VALUES (2, 'Validée');
INSERT INTO STATUT_FACTURE (CODE_STATUT, DESC_STATUT) VALUES (3, 'Réglée');
INSERT INTO STATUT_FACTURE (CODE_STATUT, DESC_STATUT) VALUES (4, 'Réclamation');
INSERT INTO STATUT_FACTURE (CODE_STATUT, DESC_STATUT) VALUES (5, 'Annulée');

